### ISSUE TITLE
Token authentication not working. Invalid audience

### ISSUE THREAD

**Issue by Thierrynjike** [jrd/django-oauth2-authcodeflow#20]
I am using the package for openidconnect on my API an it works well. 
When I am trying to consume the API from the frontend, I always get login form instead of the requested resource.
I tried to test with postman to read log and i see that the problem is with the audience retrieved from the token.

<img width="792" alt="Screenshot 2024-02-06 at 21 30 30" src="https://github.com/jrd/django-oauth2-authcodeflow/assets/39903360/93a7bf5c-9b13-40b2-a1e6-2f8f10a2ebf2">

**Comment by cpontvieux-systra** [comment]
The audience is your `OIDC_RP_CLIENT_ID`. The json web token is verified against the `OIDC_RP_SIGN_ALGOS_ALLOWED` which are `['HS256', 'HS384', 'HS512', 'RS256', 'RS384', 'RS512']` by default.

The Json web token should then contains an `AUD` key, and it’s the only key that is verified (`ISS`, `SUB`, `IAT` are not verified).

You see the direct error from the `jwt` python module : `Invalid audience` that means that you probably provided the wrong `OIDC RP_CLIENT_ID` in your configuration.
