### ISSUE TITLE
[bug] cannot logout with `django.contrib.auth.backends.ModelBackend` 

### ISSUE THREAD

**Issue by woile** [jrd/django-oauth2-authcodeflow#25]
Hi there, thanks for this package. I'm using both backends:

```py
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "oauth2_authcodeflow.auth.AuthenticationBackend",
]
```

and when I'm trying to logout, having used the `django.contrib.auth.backends.ModelBackend` to login, I get the following error:

> id_token is missing from the session, cannot logout

I think this is because of:
https://github.com/jrd/django-oauth2-authcodeflow/blob/26e5917c6ae265a06d9dc5d15c89531935156451/oauth2_authcodeflow/views.py#L341-L342

which is later used here:
https://github.com/jrd/django-oauth2-authcodeflow/blob/26e5917c6ae265a06d9dc5d15c89531935156451/oauth2_authcodeflow/views.py#L351

I think if the user has used the django backend, this check should not be done.

One possible solution is to add a blacklist, only if there's an `id_token`.

Thoughts? I can also submit a PR if needed.

Regards

**Comment by cpontvieux-systra** [comment]
Yes I had this error too (I also use the `ModelBackend` as extra backend in some of my projects).

Good catch for the reason and I think your proposition is correct.

I will propose a correction, probably tomorrow.

**Comment by woile** [comment]
Awesome! Thanks! 🎉
